#!/usr/bin/env sh

PLUGIN_FILE=~/.config/hypr/hyprland-hy3-load-plugin.conf

echo "
# AUTOGENERATED, MANUAL CHANGES WILL GET LOST
plugin = ${HY3_LOCATION}

general {
    layout = hy3
}
" > $PLUGIN_FILE

Hyprland
